apiVersion: v1
kind: Pod
metadata:
  name: mulit-container
spec: 
  terminationGracePeriodSeconds: 0
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine:3.5
    command: ["watch", "wget", "-qO-", "localhost"]
  volumes:
  - name: html-volume
    hostPath:
      path: /html
      type: Directory

