apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec: 
  terminationGracePeriodSeconds: 0
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  - name: worker
    image: nginx:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do date > /usr/share/nginx/html/index.html; sleep 1; done"]
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    hostPath:
      path: /usr/share/nginx/html
      type: DirectoryOrCreate
    
